authors:
  gde_americas:
    name: GDE Americas Team
    description: Google Developer Experts from across the Americas
    avatar: https://lh3.googleusercontent.com/a-/ALV-UjX0IA165xwhhGrII_ukKiOf1X8KVe-v0ZCciFjcyhXWCZPzAc0=s300

  # Example individual author (add your GDEs here)
  # john_doe:
  #   name: John Doe
  #   description: GDE for Android
  #   avatar: https://github.com/johndoe.png
  #   url: https://github.com/johndoe
  #   twitter: johndoe
